---
title: "Exploring variation in spotify"
output: html_notebook
---

This notebook explores variation in spotify songs using PCA.

Data was obtained from the [`R4DS Tidy Tuesday` repository](https://github.com/rfordatascience/tidytuesday/blob/master/data/2020/2020-01-21/readme.md), and it was originally compiled with the [`spotifyR` package](https://github.com/charlie86/spotifyr).


## Setup 

```{r setup}
# Load libraries
suppressPackageStartupMessages({
  library(ggplot2)
})
```


```{r}
# Read in the data
spotify_data <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-01-21/spotify_songs.csv')
```


## Principal Components Analysis

In this section, we'll calculate PCA and then plot PC2 vs PC1.

```{r}
# First, calculate PCA
pca <- spotify_data |>
  # retain only numeric data
  dplyr::select(where(is.numeric)) |>
  tidyr::drop_na() |>
  # remove any columns without variation, required for PCA calculation
  dplyr::select(where(~dplyr::n_distinct(.) > 1)) |>
  # scale and perform PCA
  scale() |>
  prcomp()

# Extract first two PCs into a data frame for plotting
pca_df <- tibble::tibble(
  PC1 = pca$x[,1],
  PC2 = pca$x[,2]
)
```


```{r}
ggplot(pca_df) + 
  aes(x = PC1, y = PC2) + 
  geom_point(color = "forestgreen", 
             size = 0.5, 
             alpha = 0.5) + 
  theme_bw()
```
