---
title: "Exploring variation in spotify"
output: html_notebook
---

This notebook explores variation in spotify songs using PCA.

Data was obtained from the [`R4DS Tidy Tuesday` repository](https://github.com/rfordatascience/tidytuesday/blob/master/data/2020/2020-01-21/readme.md), and it was originally compiled with the [`spotifyR` package](https://github.com/charlie86/spotifyr).


## Setup 

```{r setup}
# Load libraries
suppressPackageStartupMessages({
  library(ggplot2)
  library(patchwork)
})
```


```{r}
# Read in the data
spotify_data <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-01-21/spotify_songs.csv')
```


## Principal Components Analysis

In this section, we'll calculate PCA and then plot PC2 vs PC1.


```{r}
# First clean up spotify data
# this also facilitates UMAP visualization
spotify_data <- spotify_data |>
  # retain only numeric data
  dplyr::select(where(is.numeric)) |>
  tidyr::drop_na() |>
  # remove any columns without variation, required for PCA calculation
  dplyr::select(where(~dplyr::n_distinct(.) > 1))
```

```{r}
# First, calculate PCA
pca <- spotify_data |>
  scale() |>
  prcomp()

# Extract first two PCs into a data frame for plotting
pca_df <- tibble::tibble(
  PC1 = pca$x[,1],
  PC2 = pca$x[,2]
)
```


```{r}
ggplot(pca_df) + 
  aes(x = PC1, y = PC2) + 
  geom_point(color = "forestgreen", 
             size = 0.5, 
             alpha = 0.5) + 
  theme_bw()
```

## UMAP

```{r}
# Calculate UMAP itself with default parameters
umap_result <- umap(pca$x)
```

```{r}
# Extract UMAP1 and UMAP2 into a data frame
umap_df <- data.frame(umap_result$layout) |>
  # rename X1, X2 --> UMAP1, UMAP2
  dplyr::rename_all(.funs = gsub,
                    pattern = "^X",
                    replacement = "UMAP")
```

```{r}
# plot the UMAP:
ggplot(umap_df) +
  aes(x = UMAP1, y = UMAP2) +
  geom_point(alpha = 0.5,
             size = 0.1,
             color = "darkgreen") +
  # set axis limits to visualize non-outlier points
  ylim(-10, 10) + xlim(-10, 20)
```




```{r}
# Add spotify variables into umap_df
umap_full_df <- dplyr::bind_cols(
  umap_df,
  spotify_data
)

# plot the UMAP with colors that show UMAP trends
umap1 <- ggplot(umap_full_df) +
  aes(x = UMAP1, y = UMAP2, color = instrumentalness) +
  geom_point(alpha = 0.5,
             size = 0.1) +
  # set axis limits to visualize non-outlier points
  ylim(-10, 10) + xlim(-10, 20) + 
  labs(title = "Instrumentalness variable")

umap2 <- ggplot(umap_full_df) +
  aes(x = UMAP1, y = UMAP2, color = as.factor(mode)) +
  geom_point(alpha = 0.5,
             size = 0.1) +
  # set axis limits to visualize non-outlier points
  ylim(-10, 10) + xlim(-10, 20) +
  labs("Mode (major/minor scale) variable")

# stack plots with patchwork:
umap1 / umap2
```